---
- hosts: slave1
  remote_user: vagrant
  sudo: yes
  tasks:
      - name: update /root/.docker/config.json
        copy: dest=/root/.docker/config.json src=/home/vagrant/sync/mesos/config.json force=yes
