---
- hosts: master1
  remote_user: vagrant
  sudo: yes
  tasks:
      - name: install unzip package
        yum: pkg=unzip state=latest
      - name: create play directory /etc/play
        file: path=/etc/play state=directory
      - name: create log directory /var/log/play
        file: path=/var/log/play state=directory
      - name: copy play.conf to /etc/play directory
        copy: dest=/etc/play/play.conf src=/home/vagrant/sync/play/play.conf
      - name: copy open.json to /etc/play
        copy: dest=/etc/play/open.json src=/home/vagrant/sync/play/open.json
      - name: delete old play directory 
        file: path=/etc/play/open-1.0-SNAPSHOT state=absent
      - name: unzip play image and change permission to executable
        unarchive: src=/home/vagrant/sync/play/open-1.0-SNAPSHOT.zip dest=/etc/play mode=0777 owner=vagrant
      - name: start test play spark on marathon 
        shell: 'curl -X POST "http://192.168.33.11:8080/v2/apps" -d @"/etc/play/open.json" -H "Content-type: application/json"'