---
- hosts: masters
  remote_user: vagrant
  sudo: yes
  tasks:
      - name: transfer kafka folder
        synchronize: src=/home/vagrant/sync/kafka/ dest=/home/vagrant/kafka/
      - name: create log directory /var/log/kafka
        file: path=/var/log/kafka state=directory
      - name: touch /var/log/kafka/application.log
        file: path=/var/log/kafka/application.log state=touch
      - name: load from docker kwekut/kafka-mesos
        shell: sudo docker pull kwekut/kafka-mesos
      - name: start kafka on marathon 
        shell: 'curl -X POST "http://192.168.33.11:8080/v2/apps" -d @"/home/vagrant/kafka/kafka.json" -H "Content-type: application/json"'